name: Automated Code Formatting

on:
  push:
  pull_request:

jobs:

  Format:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2.3.4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1.8.0
      with:
        dotnet-version: 5.0.x
    - name: Restore tools
      run: dotnet tool restore
    - name: Run dotnet format
      run: find . -type f -name "*.csproj" -or -name "*.vbproj" | xargs --max-args=1 --no-run-if-empty dotnet format
    - name: Run fantomas
      run: find . -type f -name "*.fs" -or -name "*.fsx" | xargs --no-run-if-empty dotnet fantomas
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4.11.0
      with:
        commit_message: Automated formatting
